# --- MySQL on Railway (from local machine) ---
spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:53189/railway?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.datasource.username=root
spring.datasource.password=AdAuFqpwVtVBsDdHbyttkFRQiFGBBUEo
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Disable H2 init script for now (data.sql uses H2-specific MERGE)
spring.sql.init.mode=never