# Konfiguracja bazy danych H2 (do testów)
spring.datasource.url=jdbc:h2:file:./data/fleetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Konfiguracja JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Konsola H2 (opcjonalnie, do debugowania)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Inicjalizacja danych
spring.sql.init.mode=always

